name: tes
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  get_cli: ^1.8.4
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4
  get: ^4.6.6
  http: ^0.13.6
  webview_flutter: ^4.4.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

